[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "NOTAIRFLOW"
version = "0.0.1"
authors = [
  { name="Thanh Tu, Do", email="tu.dothanh1906@gmail.com" },
]
description = "A ismall example package implementing Airflow DAG: structured job consist of multiple task and its dependency"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "iamtu.dev"
Issues = "https://github.com/pypa/sampleproject/issues"
